<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/**
 * @var $this Amasty_Shopby_Block_Catalog_Layer_Filter_Attribute
 */
?><ol class="
<?php if ($this->getCollapsed() && !$this->getHasSelection()): ?>no-display-current<?php endif ?>
<?php
	if ($this->getSortFeaturedFirst() && in_array($this->getDisplayType(), array(Amasty_Shopby_Model_Source_Attribute::DT_LABELS_ONLY, Amasty_Shopby_Model_Source_Attribute::DT_IMAGES_AND_LABELS))):
	?>sort-featured-first-<?php echo $this->getRequestValue(); endif ?>
">
	<?php if ($this->getSortFeaturedFirst()): ?><input type="hidden" id="field_sort_featured_<?php echo $this->getRequestValue();?>" value="default_sort"><?php endif ?>
<?php
switch ($this->getDisplayType()){
    case Amasty_Shopby_Model_Source_Attribute::DT_LABELS_ONLY:
        if ($this->getShowSearch()){
            echo '<li rel="search"><input type="text" class="amshopby_attr_search input-text" onkeyup="amshopby_attr_search(this)" /></li>';
        }
        /* attribute groups code goes from here */

        $items = $this->getItemsAsArray();

            $item1 = $items[0];
            $name1 = $item1['label'];
            if (strpos($name1, '>') !== false) { // if attribute name contains '>', start grouping
                $groups = array();
                // group options based on the option names

                foreach ($items as $item) {
                    $name = $item['label'];
                    $preName = array_shift(explode('>', $name));
                    $item['preName'] = $preName;
                    $item['opName'] = substr($name, strpos($name, ">")+1);
                    if (array_key_exists($preName, $groups)){
                        $groups[$preName][] = $item;
                    }
                    else {
                        $groups[$preName] = array($item);
                    }
                }

                // render filters
                foreach ($groups as $groupName=>$groupItems) {
                    echo '<li>'.
                        '<div class="att-group-title">' .
                        $groupName.
                        '</div>'.
                        '<ol class="att-group-items">';

                    foreach($groupItems as $groupItem) {
                        echo '<li '.
                            (isset($groupItem['style']) ? $groupItem['style'] : '') .
                            (isset($groupItem['default_sort']) ? ' data-default_sort="' . $groupItem['default_sort'] . '"': '') .
                            (isset($groupItem['featured_sort']) ? ' data-featured_sort="' . $groupItem['featured_sort'] . '"': '') .
                            'data-text="' . htmlspecialchars($groupItem['opName']) . '"> ' .
                            '<a class="'.$groupItem['css'].'"' . $groupItem['rel'] . ' href="'.$groupItem['url'].'">'. $groupItem['opName'] . $groupItem['count'] . '</a>' .
                            '</li>';
                    }

                    echo '</ol>'.
                        '</li>';
                }

            }

else {/* end of attribute groups code */
    foreach ($this->getItemsAsArray() as $item) {
        echo
            '<li ' .
            (isset($item['style']) ? $item['style'] : '') .
            (isset($item['default_sort']) ? ' data-default_sort="' . $item['default_sort'] . '"' : '') .
            (isset($item['featured_sort']) ? ' data-featured_sort="' . $item['featured_sort'] . '"' : '') .
            'data-text="' . htmlspecialchars($item['label']) . '"> ' .
            '<a class="' . $item['css'] . '"' . $item['rel'] . ' href="' . $item['url'] . '">' . $item['label'] . $item['count'] . '</a>' .
            '</li>';
    }

}
    break;

case
    Amasty_Shopby_Model_Source_Attribute::DT_IMAGES_ONLY:
        echo '<li>';
        foreach ($this->getItemsAsArray() as $item) {
            if (isset($item['image_hover']) && $item['image_hover'] != '') {
                echo '<img src="' . $item['image_hover'] . '" style="display: none;" />';
                $onHover = 'onmouseover=this.src="' . $item['image_hover'] . '"';
                $onHover .= ' onmouseout=this.src="' . $item['image'] . '"';
            } else {
                $onHover = '';
            }
            echo '<a ' . $item['style'] . $item['rel'] . ' class="' . $item['css'] . '" href="' . $item['url'] . '"><img src="' . $item['image'] . '" ' . $onHover . ' title="' . $item['label'] . '" alt="' . $item['label'] . '"></a>';

        }
        echo '</li>';
    break;
    
    case Amasty_Shopby_Model_Source_Attribute::DT_IMAGES_AND_LABELS:
        if ($this->getShowSearch()) {
            echo '<li rel="search"><input type="text" class="amshopby_attr_search" onkeyup="amshopby_attr_search(this)" /></li>';
        }
        foreach ($this->getItemsAsArray() as $item) {
            echo '<li ' . $item['style'] .
                (isset($item['default_sort']) ? ' data-default_sort="' . $item['default_sort'] . '"' : '') .
                (isset($item['featured_sort']) ? ' data-featured_sort="' . $item['featured_sort'] . '"' : '') .
                ' data-text="' . htmlspecialchars($item['label']) . '"><a class="' . $item['css'] . '" ' . $item['rel'] . ' href="' . $item['url'] . '">';

            if (isset($item['image_hover']) && $item['image_hover'] != '') {
                echo '<img src="' . $item['image_hover'] . '" style="display: none;" />';
                $onHover = 'onmouseover=this.src="' . $item['image_hover'] . '"';
                $onHover .= ' onmouseout=this.src="' . $item['image'] . '"';
            } else {
                $onHover = '';
            }

            if (!empty($item['image'])) {
                echo '<img src="' . $item['image'] . '" ' . $onHover . ' title="' . $item['label'] . '" alt="' . $item['label'] . '">';
            }
            echo $item['label'] . $item['count'] . '</a>' . '</li>';
        }

    break;
    
    case Amasty_Shopby_Model_Source_Attribute::DT_DROPDOWN:
        echo '<li><select onchange="if (this.value) setLocation(this.value)" class="amshopby-select amshopby-ajax-select">';
        echo '<option value="'.$this->getRemoveUrl().'">&nbsp;</option>';
        foreach ($this->getItemsAsArray() as $item){
            echo '<option '.$item['css'] . $item['rel'] . ' value="'.$item['url'].'">'. $item['label'] . $item['count'] . '</option>';
        }
        echo '</select></li>';
    break;
    
    case Amasty_Shopby_Model_Source_Attribute::DT_LABELS_IN_2_COLUMNS:
        $items = $this->getItemsAsArray();
        $size  = sizeof($items);
        $half  =  ceil($size/2);
        $third = ceil($size/3);
        $quarter = ceil($size/4);
        $breakPoint = 20;


        if ($size <= 5) {
            echo '<li>';
            echo '<div>';
            for ($i=0; $i< $size; $i++){
                $item = $items[$i];
                echo '<a class="'.$item['css'].'" '.$item['rel'].' href="'.$item['url'].'" data-text="' . htmlspecialchars($item['label']) . '">'. $item['label'] . $item['count'] . '</a>' . '<br/>';
            }
            echo '</div>';
            echo '</li>';
        }

        else if ($size < $breakPoint) {
            echo '<li>';
            echo '<div class="amshopby-column">';
            for ($i=0; $i<$half; $i++){
                $item = $items[$i];
                echo '<a class="'.$item['css'].'" '.$item['rel'].' href="'.$item['url'].'" data-text="' . htmlspecialchars($item['label']) . '">'. $item['label'] . $item['count'] . '</a>' . '<br/>';
            }
            echo '</div>';
            echo '<div class="amshopby-column">';
            for ($i=$half; $i<$size; $i++){
                $item = $items[$i];
                echo '<a class="'.$item['css'].'" '.$item['rel'].' href="'.$item['url'].'" data-text="' . htmlspecialchars($item['label']) . '">'. $item['label'] . $item['count'] . '</a>' . '<br/>';
            }
            echo '</div>';
            echo '</li>';
        }
        else {
            echo '<li class="columns-4">';
            echo '<div class="amshopby-column">';
            for ($i=0; $i<$quarter; $i++){
                $item = $items[$i];
                echo '<a class="'.$item['css'].'" '.$item['rel'].' href="'.$item['url'].'" data-text="' . htmlspecialchars($item['label']) . '">'. $item['label'] . $item['count'] . '</a>' . '<br/>';
            }
            echo '</div>';

            echo '<div class="amshopby-column">';
            for ($i=$quarter; $i<2*$quarter; $i++){
                $item = $items[$i];
                echo '<a class="'.$item['css'].'" '.$item['rel'].' href="'.$item['url'].'" data-text="' . htmlspecialchars($item['label']) . '">'. $item['label'] . $item['count'] . '</a>' . '<br/>';
            }
            echo '</div>';

            echo '<div class="amshopby-column">';
            for ($i=2*$quarter; $i<3*$quarter; $i++){
                $item = $items[$i];
                echo '<a class="'.$item['css'].'" '.$item['rel'].' href="'.$item['url'].'" data-text="' . htmlspecialchars($item['label']) . '">'. $item['label'] .$item['count'] .  '</a>' . '<br/>';
            }
            echo '</div>';

            echo '<div class="amshopby-column">';
            for ($i=3*$quarter; $i<$size; $i++){
                $item = $items[$i];
                echo '<a class="'.$item['css'].'" '.$item['rel'].' href="'.$item['url'].'" data-text="' . htmlspecialchars($item['label']) . '">'. $item['label'] . $item['count'] . '</a>' . '<br/>';
            }
            echo '</div>';
            echo '</li>';
        }
    break;
}

if ($this->getShowLessMore() && in_array($this->getDisplayType(), array(
        Amasty_Shopby_Model_Source_Attribute::DT_LABELS_ONLY,
        Amasty_Shopby_Model_Source_Attribute::DT_IMAGES_ONLY,
        Amasty_Shopby_Model_Source_Attribute::DT_IMAGES_AND_LABELS,
    ))) {

    $total = count($this->getItemsAsArray());
    $short = $this->getMaxOptions();
    $add = $total - $short;
    if ($add > 0) {
        $text = sprintf($this->__('View %d More'), $add);
        echo '<li class="amshopby-clearer"><a id="amshopby-more-'.$this->getRequestValue().'" class="amshopby-more" href="#">' . $text . '</a></li>';
    }
    echo '<li class="amshopby-clearer"><a id="amshopby-less-'.$this->getRequestValue().'" class="amshopby-less" href="#" style="display:none">' . $this->__('Show Less') . '</a></li>';
} 
?>
</ol>