<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php $_removeTxt = Mage::helper('catalog')->__('Remove This Item') ?>
<?php if (!empty($_filters)): ?>
    <p class="block-subtitle"><?php echo Mage::helper('catalog')->__('Currently Shopping by') ?></p>
    <div class="currently">
        <ol>
            <?php foreach ($_filters as $_filter):?>
                <li class="current-filter">
                    <span class="label" data-title="<?php echo str_replace(' ', '', strtolower(Mage::helper('catalog')->__($_filter->getName()))); ?>"><?php echo Mage::helper('catalog')->__($_filter->getName()) ?>:</span>
                    <?php if ($_filter->hasData('children')): ?>
                        <?php foreach ($_filter->getData('children') as $child): ?>
                            <?php
                            $label = $child['label'];
                            if (strpos($label, '>') !== false) {
                                $label = substr($label, strpos($label, ">")+1);
                            }
                            ?>

                            <span class="multiselect-child <?php echo  $label  ?>">
                                <?php echo  $label  ?>
                                <a href="<?php echo $child['url'] ?>" class="btn-remove-inline">
                                    <img src="<?php echo Mage::getDesign()->getSkinUrl('images/spacer.gif') ?>" width="13" height="12" alt="<?php echo $_removeTxt ?>" />
                                </a>
                            </span>
                        <?php endforeach ?>
                    <?php else: ?>
                        <?php
                        $label = $_filter->getLabel();
                        if (strpos($label, '>') !== false) {
                            $label = substr($label, strpos($label, ">")+1);
                        }
                        ?>
                        <span class="single-child">
                        <span <?php if(Mage::helper('catalog')->__($_filter->getName()) == "Color"): ?>class="<?php echo $_filter->getLabel(); ?> " <?php endif;?>><?php echo $label ?></span>
                        <a href="<?php echo $_filter->getRemoveUrl() ?>" class="btn-remove" title="<?php echo $_removeTxt ?>"><?php echo $_removeTxt ?></a></span>

                    <?php endif ?>
                </li>
            <?php endforeach; ?>
        </ol>
        <?php if (!method_exists('Mage', 'getEdition')): // CE 1.7+, EE 1.12+?>
            <div class="actions"><a href="<?php echo $this->getParentBlock()->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
    </div>


<?php endif; ?>
