<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php $_removeTxt = Mage::helper('catalog')->__('Remove This Item') ?>
<?php if (!empty($_filters)): ?>
    <p class="block-subtitle"><?php echo Mage::helper('catalog')->__('Currently Shopping by') ?></p>
    <div class="currently">
        <ol>
            <?php foreach ($_filters as $_filter):?>
                <li class="current-filter">
                    <span class="label" data-title="<?php echo str_replace(' ', '', strtolower(Mage::helper('catalog')->__($_filter->getName()))); ?>"><?php echo Mage::helper('catalog')->__($_filter->getName()) ?>:</span>
                    <?php if ($_filter->hasData('children')): ?>
                        <?php foreach ($_filter->getData('children') as $child): ?>
                            <span class="multiselect-child">
                                <?php echo $child['label']  ?>
                                <a href="<?php echo $child['url'] ?>" class="btn-remove-inline">
                                    <img src="<?php echo Mage::getDesign()->getSkinUrl('images/spacer.gif') ?>" width="13" height="12" alt="<?php echo $_removeTxt ?>" />
                                </a>
                            </span>
                        <?php endforeach ?>
                    <?php else: ?>
                        <a href="<?php echo $_filter->getRemoveUrl() ?>" class="btn-remove" title="<?php echo $_removeTxt ?>"><?php echo $_removeTxt ?></a>
                        <?php echo $_filter->getLabel() ?>
                    <?php endif ?>
                </li>
            <?php endforeach; ?>
        </ol>
        <?php if (!method_exists('Mage', 'getEdition')): // CE 1.7+, EE 1.12+?>
            <div class="actions"><a href="<?php echo $this->getParentBlock()->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
    </div>


    <script>
        jQuery(function($) {
            var currentFilter = $('.current-filter');
            var filters = $('.amshopby-item-top');

            currentFilter.each(function(){
                for (var i= 0; i < filters.length; i++) {
                    var filter = $(filters[i]);

                    if ($(this).find('.label').data('title') == (filter.find('dl').data('title'))) {
                        $(this).appendTo(filter);
                        $(this).find('.label').hide();

                    }
                }

            })

        });

    </script>

<?php endif; ?>
