<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php if($this->canShowBlock()): ?>
    <div id="am-top-nav" class="block block-layered-nav">
        <div class="block-title">
            <strong><span><?php echo $this->__('Narrow Your Search') ?></span></strong>
        </div>
        <div class="block-content">
            <?php echo $this->getStateHtml() ?>
            <?php if ($this->getLayer()->getState()->getFilters() && method_exists('Mage', 'getEdition')): // CE 1.7+, EE 1.12+?>

                <div class="actions"><a href="<?php echo Mage::helper('amshopby/url')->getFullUrl(array(), 1) ?>">
                        <?php echo Mage::helper('catalog')->__('Clear All Filters') ?></a>
                </div>
                <div class="hide-nav"><?php echo $this->__('Hide Filters');?></div>
            <?php endif; ?>
            <?php if($this->canShowOptions()): ?>
                    <div class="amshopby-container-top block-layered-nav">
                        <?php foreach ($this->getFilters() as $_filter): ?>
                            <?php if($_filter->getItemsCount()): ?>
                                <?php  $position = Mage::helper('amshopby')->getAttributePosition($_filter); ?>
                                <div class="amshopby-item-top block-content am-toggle-content">
                                    <dl id="narrow-by-list" class="amshopby-narrow-by-list" data-title="<?php echo str_replace(' ', '', strtolower($this->__($_filter->getName())))?>" data-position="<?php echo $position;?>">
                                        <?php if ($_filter->getAttributeCode() == 'price') : ?>
                                            <?php $_filter->addData(array('amprice-position' => 'top')); ?>
                                        <?php
                                        endif; ?>
                                        <dt><?php echo $this->__($_filter->getName()) ?></dt>
                                        <dd><?php echo $_filter->getHtml() ?></dd>
                                    </dl>
                                </div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                <script type="text/javascript">decorateDataList('narrow-by-list')</script>

                <script type="text/javascript">
                   jQuery(function($) {
                       // hide filters
                       //$('body').off().on('click', '.hide-filter', function(){


                      // });


                       // toggle filters
                          $('body').off().on('click','.amshopby-narrow-by-list > dt', function(){
                              // for desktop only
                              if (!window.matchMedia('(max-width: 770px)').matches ) {
                                  $(".amshopby-narrow-by-list > dd").hide();

                                  var filterContent = $(this).siblings('dd');

                                  if (filterContent.hasClass('open')) {
                                      filterContent.removeClass('open');
                                      filterContent.hide();
                                      $(this).removeClass('open');

                                  }
                                  else {
                                      $(".amshopby-narrow-by-list > dd").removeClass('open');
                                      $('.amshopby-narrow-by-list > dt').removeClass('open');
                                      filterContent.show();
                                      filterContent.addClass('open');
                                      $(this).addClass('open');
                                  }
                              }

                              return false;
                           });
                    });

                </script>

            <?php // to move top layered nav and fix a bug that in some page the position of top layered nav is not correct?>
                <script>
                    /*jQuery(function($){

                        $(document).ready(function(){

                            var toolBar = $('#amshopby-page-container').find('.toolbar');
                            var topNav = $('#am-top-nav');
                            /!*console.log(toolBar);
                            if (toolBar.length){
                                topNav.insertAfter(toolBar);
                            }
                            else {
                                topNav.insertAfter($('#amshopby-page-container .category-title'));
                            }*!/
                            console.log($('#amshopby-page-container .category-title'))
                            topNav.insertAfter($('#amshopby-page-container .category-title'));

                        });

                    });*/
                </script>

            <?php endif; ?>
        </div>
    </div>

<?php else: ?>
    <div style="display:none" class="<?php echo $this->getBlockId()?>"></div>
<?php endif; ?>

