<?php $bgUrl = $this->getSkinUrl('images/nav_bground.gif');?>

<table>
    <tr style="background: url('<?php echo $bgUrl ?>') repeat-x center center; background-size: contain;color: #fff;">
        <td style="text-align:center;text-transform: uppercase;padding: 15px 10px;">
            Signs & Wall Decor
        </td>
        <td style="text-align:center;text-transform: uppercase;padding: 15px 10px;">
            What's New
        </td>
        <td style="text-align:center;text-transform: uppercase;padding: 15px 10px;">
           Best Sellers
        </td>
        <td style="text-align:center;text-transform: uppercase;padding: 15px 10px;">
            Specials
        </td>
    </tr>
    <tr>
        <td style="font-size:26px;width:100%;padding:40px 20px 15px" colspan="4">
            <img style="vertical-align:top;" src="<?php echo $this->getSkinUrl('images/cart-blk.png')?>" width="35" height="30"/> <strong style="font-weight:bold;text-transform: uppercase;"> Smile! </strong> Your cart is saved!
        </td>
    </tr>
</table>