
<?php $baseUrl = Mage::getBaseUrl();?>

<table>
    <tr>
        <td style="padding: 10px 20px;">
            <table>
                <tr>
                    <td>
                        <a style="background-color: #7E221B;padding: 12px 0;color: #FFFFFF;text-transform: uppercase;text-decoration: none;font-size:16px;display:block;text-align:center;width:100%;" href="<?php echo $baseUrl . 'checkout/onepage'?>">Proceed to Check out &rsaquo;  </a>
                    </td>
                </tr>
                <tr>
                    <td style="text-align:center;padding:20px 0 10px;">
                        Let's Connect. Follow us Today!
                    </td>
                </tr>
                <tr>
                    <td style="text-align:center;">
                        <a title="Facebook" href="https://www.facebook.com/primitivesbykathy" target="_blank"><img alt="" src="<?php echo $this->getSkinUrl('images/icons/facebook.png')?>"></a>
                        <a title="Pinterest" href="http://pinterest.com/pbkathy/" target="_blank"><img alt="" src="<?php echo $this->getSkinUrl('images/icons/p.png')?>"></a>
                        <a title="Google+" href="https://plus.google.com/+PrimitivesKathy/about" target="_blank"><img alt="" src="<?php echo $this->getSkinUrl('images/icons/g.png')?>"></a>
                        <a title="Instagram" href="https://www.instagram.com/primitivesbykathy/" target="_blank"><img alt="" src="<?php echo $this->getSkinUrl('images/icons/i.png')?>"></a>
                        <a title="Youtube" href="https://www.youtube.com/user/PBKInc/" target="_blank"><img alt="" src="<?php echo $this->getSkinUrl('images/icons/youtube.png')?>"></a>
                        <a href="#" target="_blank"><img alt="" src="<?php echo $this->getSkinUrl('images/icons/b.png')?>"></a>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td style="padding: 20px 0;">
            <table>
                <tr style="background: url('<?php echo $this->getSkinUrl('images/footer_bground.gif'); ?>') repeat center center; background-size: auto;">
                    <td style="padding: 20px;">
                        <a href="<?php echo $baseUrl; ?>">
                        <img width="160" height="auto"
                        src="<?php echo $this->getSkinUrl('images/logo.gif')?>"
                        alt="Primitives by Kathy"
                        border="0"/>
                        </a>
                    </td>
                    <td style="text-align:center;padding: 20px;vertical-align:middle;">
                        <p style="margin:0;">
                            <strong style="font-weight:bold;">1.866.BYKATHY</strong> (295.2849)
                        </p>
                        <p style="margin:0;">1817 William Penn Way | Lancaster, PA 17601</p>
                        <p style="margin:0;"><a href="<?php echo $baseUrl?>">www.primitivesbykathy.com</a></p>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

