<?php

/**
 * MageWorx
 * CustomOptions Extension
 *
 * @category   MageWorx
 * @package    MageWorx_CustomOptions
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */

$_option = $this->getOption();
$_optionId = $_option->getId();
$helper = Mage::helper('mageworx_customoptions');
?>
<div <?php if ($helper->hideDependentOption() && $_option->getIsDependent() || $_option->getViewMode()==2) { ?>style="display: none;"<?php } ?> class="option<?php if ($helper->isSpecifyingCssClassEnabled() && $_option->getDivClass()) echo ' '.$_option->getDivClass() ?>">
<dl>
<dt><label><?php echo  $this->htmlEscape($_option->getTitle()) ?><?php if ($_option->getIsRequire(true)): ?><span class="required">&nbsp;*</span><?php endif; ?></label>
    <?php echo $helper->getFormatedOptionPrice($this->getProduct(), $_option); ?>
    <?php echo $helper->getOptionDescription($_option); ?>
</dt>

<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
    Requested Ship Date:<br/>
<?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE_TIME || $_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE): ?>

    <?php echo $this->getDateHtml() ?>

    <?php if (!$this->useCalendar()): ?>
    <script type="text/javascript">
    //<![CDATA[
        Event.observe('options_<?php echo $_optionId ?>_month', 'change', dateOption.reloadMonth.bind(dateOption));
        Event.observe('options_<?php echo $_optionId ?>_year', 'change', dateOption.reloadMonth.bind(dateOption));
    //]]>
    </script>
    <?php endif; ?>

<?php endif; ?>

<?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE_TIME
    || $_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_TIME): ?>
    &nbsp;&nbsp;<?php echo $this->getTimeHtml() ?>
<?php endif; ?>

    <input type="hidden" name="validate_datetime_<?php echo $_optionId ?>" class="validate-datetime-<?php echo $_optionId ?>" value="" />
    <script type="text/javascript">
    //<![CDATA[
<?php if ($_option->getIsRequire(true)): ?>
        Validation.addAllThese(
        [
               ['validate-datetime-<?php echo $_optionId ?>', '<?php echo $helper->__js('This is a required option') ?>', function(v) {
                   var dateTimeParts = $$('.datetime-picker[id^="options_<?php echo $_optionId ?>"]');
                   for (var i=0; i < dateTimeParts.length; i++) {
                        if(dateTimeParts[i].disabled === true) {
                           return true;
                       }
                       if (dateTimeParts[i].value == "") return false;
                   }
                   return true;
                }]
        ]
        );
<?php else: ?>
        Validation.add(
            'validate-datetime-<?php echo $_optionId ?>',
            '<?php echo $helper->__js('Field is not complete') ?>',
            function(v) {
                var dateTimeParts = $$('.datetime-picker[id^="options_<?php echo $_optionId ?>"]');
                var hasWithValue = false, hasWithNoValue = false;
                var pattern = /day_part$/i;
                for (var i=0; i < dateTimeParts.length; i++) {
                   if (! pattern.test(dateTimeParts[i].id)) {
                       if (dateTimeParts[i].value === "") {
                           hasWithValue = true;
                       } else {
                           hasWithNoValue = true;
                       }
                   }
                }
                return hasWithValue ^ hasWithNoValue;
            }
        );
<?php endif;

if ($helper->isDependentEnabled() && $_option->getIsDependent()) { ?>
    $$('.product-custom-option[id^="options_<?php echo $_optionId ?>_"]').each(function(dt){
        dt.disabled = true;
    });
<?php } ?>
    //]]>
    </script>
        <input type="hidden" class="option_value" id="value_option_<?php echo $_option->getId() ?>" value="0" />
</dd>
</dl>
</div>
<script type="text/javascript">
    jQuery(document).ready(function($) {
        // set checkbox to checked
        //$('input.check_z').prop('checked', true);

        // toggle options

        var dateOptionWrapper = $("#product-options-wrapper").find('.ship-date');

        //append text and click link
        var hideOptionSpanWrapper = document.createElement('span');
        var hideOptionSpan = document.createElement('span');
        var clickSpan = document.createElement('span');
        $(clickSpan).addClass('red-link open');
        clickSpan.innerHTML = " click here.";
        hideOptionSpan.innerHTML=' Hide future ship date,';
        hideOptionSpanWrapper.appendChild(hideOptionSpan);
        hideOptionSpanWrapper.appendChild(clickSpan);
        var optionTitle = dateOptionWrapper.find('label');
        optionTitle.append(hideOptionSpanWrapper);

        // click effect
        var dateOption = dateOptionWrapper.find('dd');
        $(clickSpan).click(function(){
            if ($(this).hasClass('open')) {
                dateOption.hide();
                $(this).removeClass('open');
                $(this).addClass('close');
                hideOptionSpan.innerHTML=' Request future ship date,';
            }
            else {
                dateOption.show();
                $(this).removeClass('close');
                $(this).addClass('open');
                hideOptionSpan.innerHTML=' Hide future ship date,';
            }
        })

    });
</script>