<div class="storeviews">
<?php

$domain = Mage::getBaseUrl (Mage_Core_Model_Store::URL_TYPE_WEB);
$trashtalk = $domain . 'trashtalk';
$questionables = $domain . 'questionables';

$storeId = Mage::app()->getStore()->getStoreId();
?>
    <?php if($storeId == 2 || $storeId == 5): // retail trashtalk or retail questionalble
        ?>
    <a href="<?php echo $domain?>"> Retail </a>
    <?php elseif ($storeId == 4 || $storeId == 6): // wholesale trashtalk or wholesale questionalble
        ?>
    <a href="<?php echo $domain?>"> Wholesale </a>
    <?php endif; ?>

    <?php if($storeId != 2 && $storeId != 4): // not trashtalk
        ?>
    <a href="<?php echo $trashtalk?>"> Trash Talk </a>
    <?php endif; ?>
    <?php if($storeId != 5 && $storeId != 6): // not questionable
    ?>
    <a href="<?php echo $questionables?>"> Questionables </a>
    <?php endif; ?>
</div>