<style type="text/css">

    /* Media Queries here */
    @media (min-width: 476px) {
        .row-on-mobile {
            display: none;
        }

        .row-on-desktop {
            display: table-row;
        }
    }

    @media (max-width: 475px) {
        .row-on-mobile {
            display: table-row !important;
        }

        .row-on-desktop {
            display: none;
        }

        .full-width {
            width: 100% !important;
        }

        .social-icon-list {
            padding-top: 1.3em !important;
        }

        .social-icon {
            padding-right: .3em !important;
        }
    }
</style>


<table style="width: 600px; margin: auto; background: #fff;" border="0" cellpadding="0" cellspacing="0"><!--start of email wrapper-->
    <tr>
        <td>
            <table style="width: 100%;" border="0" cellpadding="0" cellspacing="0"><!--start of head table-->
                <tr>
                    <td bgcolor="#ffffff" align="center" valign="top" style="padding-top: 5px; padding-bottom: 20px;">
                        <a target="_blank" href="{{store url=''}}"><img src="https://smhttp-ssl-52639.nexcesscdn.net/skin/frontend/rwd/pbk/images/logo.gif" alt="Primitives by Kathy" border="0" style="width: 35%"></a>
                    </td>
                </tr>

                <tr class="row-on-desktop">
                    <td valign="top">
                        <table style="width: 100%;" border="0" cellpadding="0" cellspacing="0">
                            <tr bgcolor="#7F221B">
                                <td valign="top">
                                    <a href="{{store url=''}}everyday" style="display: block; color: #fff; text-decoration: none; text-align: center; padding-top: 0.7em; padding-bottom: 0.7em;">Gift &amp; Decor</a>
                                </td>

                                <td valign="top">
                                    <a href="{{store url=''}everyday/shopby/category_filter-signs_wall_decor_box_signs" style="display: block; color: #fff; text-decoration: none; text-align: center; padding-top: 0.7em; padding-bottom: 0.7em;">Box Signs</a>
                                </td>

                                <td valign="top">
                                    <a href="{{store url=''}}seasonal" style="display: block; color: #fff; text-decoration: none; text-align: center; padding-top: 0.7em; padding-bottom: 0.7em;">Seasonal</a>
                                </td>

                                <td valign="top">
                                    <a href="{{store url=''}}collection" style="display: block; color: #fff; text-decoration: none; text-align: center; padding-top: 0.7em; padding-bottom: 0.7em;">Collections</a>
                                </td>

                                <td valign="top">
                                    <a href="{{store url=''}}all-new" style="display: block; color: #fff; text-decoration: none; text-align: center; padding-top: 0.7em; padding-bottom: 0.7em;">All New</a>
                                </td>

                                <td valign="top">
                                    <a href="{{store url=''}}on-sale" style="display: block; color: #fff; text-decoration: none; text-align: center; padding-top: 0.7em; padding-bottom: 0.7em;">On Sale</a>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>

                <tr class="row-on-mobile" style="display: none;">
                    <td valign="top">
                        <table style="width: 100%;" border="0" cellpadding="0" cellspacing="0">
                            <tr bgcolor="#7F221B">
                                <td valign="top">
                                    <a href="{{store url=''}}/everyday" style="display: block; color: #fff; text-decoration: none; text-align: center; padding-top: 0.7em; padding-bottom: 0.7em;">Gift &amp; Decor</a>
                                </td>

                                <td valign="top">
                                    <a href="{{store url=''}everyday/shopby/category_filter-signs_wall_decor_box_signs" style="display: block; color: #fff; text-decoration: none; text-align: center; padding-top: 0.7em; padding-bottom: 0.7em;">Box Signs</a>
                                </td>

                                <td valign="top">
                                    <a href="{{store url=''}}seasonal" style="display: block; color: #fff; text-decoration: none; text-align: center; padding-top: 0.7em; padding-bottom: 0.7em;">Seasonal</a>
                                </td>
                            </tr>

                            <tr bgcolor="#7F221B">
                                <td valign="top">
                                    <a href="{{store url=''}}collection" style="display: block; color: #fff; text-decoration: none; text-align: center; padding-top: 0.7em; padding-bottom: 0.7em;">Collections</a>
                                </td>

                                <td valign="top">
                                    <a href="{{store url=''}}all-new" style="display: block; color: #fff; text-decoration: none; text-align: center; padding-top: 0.7em; padding-bottom: 0.7em;">All New</a>
                                </td>

                                <td valign="top">
                                    <a href="{{store url=''}}on-sale" style="display: block; color: #fff; text-decoration: none; text-align: center; padding-top: 0.7em; padding-bottom: 0.7em;">On Sale</a>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table><!--end of head table-->