<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php if(!$_productCollection->count()): ?>
    <div class="note-msg">
        <?php echo $this->__('There are no products matching the selection. Please provide a category ID.') ?>
    </div>
<?php else: ?>

    <?php // Grid Mode ?>


    <ul id="featured" class="jcarousel-skin-tango">

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <?php if($i++%4==0): ?>


            <?php endif ?>



            <li><a class="preview" rel="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300, 300); ?>" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(105, 105); ?>" width="105" height="105" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                </a> </li>

            <?php if ($i%4==0 && $i!=$_collectionSize): ?>

            <?php endif ?>


        <?php endforeach ?>


    </ul>


<?php endif; ?>